openapi: 3.0.1
info:
  title: E-commerce API
  description: API documentation for the E-commerce application
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /api/products:
    get:
      summary: Get all products
      tags: 
        - Products
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
          description: Limit the number of products returned
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 1
          description: The page number for pagination
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '404':
          description: No products found
        '500':
          description: Internal server error

  /api/products/{pid}:
    get:
      summary: Get product by ID
      tags: 
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          schema:
            type: string
          description: The ID of the product to retrieve
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found
        '500':
          description: Internal server error

    put:
      summary: Update product by ID
      tags: 
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          schema:
            type: string
          description: The ID of the product to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Product updated successfully
        '404':
          description: Product not found
        '403':
          description: Unauthorized to update this product
        '500':
          description: Internal server error

    delete:
      summary: Delete product by ID
      tags: 
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          schema:
            type: string
          description: The ID of the product to delete
      responses:
        '200':
          description: Product deleted successfully
        '404':
          description: Product not found
        '403':
          description: Unauthorized to delete this product
        '500':
          description: Internal server error

  /api/carts:
    post:
      summary: Create a new cart
      tags: 
        - Carts
      responses:
        '201':
          description: Cart created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '500':
          description: Internal server error

  /api/carts/{cid}:
    get:
      summary: Get cart by ID
      tags: 
        - Carts
      parameters:
        - name: cid
          in: path
          required: true
          schema:
            type: string
          description: The ID of the cart to retrieve
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        '404':
          description: Cart not found
        '500':
          description: Internal server error

    post:
      summary: Add product to cart
      tags: 
        - Carts
      parameters:
        - name: pid
          in: path
          required: true
          schema:
            type: string
          description: The ID of the product to add to the cart
      responses:
        '200':
          description: Product added to cart successfully
        '404':
          description: Cart or Product not found
        '500':
          description: Internal server error

  /api/users:
    get:
      summary: Get all users (Admin only)
      tags: 
        - Users
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '500':
          description: Internal server error

    post:
      summary: Register a new user
      tags: 
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Invalid input
        '500':
          description: Internal server error

  /api/users/{uid}/documents:
    post:
      summary: Upload documents for a user
      tags: 
        - Users
      parameters:
        - name: uid
          in: path
          required: true
          schema:
            type: string
          description: The ID of the user
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                profile:
                  type: string
                  format: binary
                product:
                  type: string
                  format: binary
                document:
                  type: string
                  format: binary
      responses:
        '200':
          description: Documents uploaded successfully
        '404':
          description: User not found
        '500':
          description: Internal server error

  /api/users/{uid}/premium:
    post:
      summary: Upgrade user to premium
      tags:
        - Users
      parameters:
        - name: uid
          in: path
          required: true
          schema:
            type: string
          description: The ID of the user to upgrade
      responses:
        '200':
          description: User upgraded to premium successfully
        '404':
          description: User not found or missing documents
        '500':
          description: Internal server error

  /api/ticket/{tid}:
    get:
      summary: Get ticket by ID
      tags:
        - Tickets
      parameters:
        - name: tid
          in: path
          required: true
          schema:
            type: string
          description: The ID of the ticket to retrieve
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
        '404':
          description: Ticket not found
        '500':
          description: Internal server error

  /api/sessions/current:
    get:
      summary: Get current session
      tags:
        - Sessions
      responses:
        '200':
          description: Current session details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '500':
          description: Internal server error

  /api/email/send:
    post:
      summary: Send an email
      tags:
        - Email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                to:
                  type: string
                  description: Recipient email address
                subject:
                  type: string
                  description: Email subject
                text:
                  type: string
                  description: Email content
      responses:
        '200':
          description: Email sent successfully
        '500':
          description: Failed to send email

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        price:
          type: number
        stock:
          type: integer
      example:
        id: "607c191e810c19729de860ea"
        title: "Product A"
        description: "Description of Product A"
        price: 100
        stock: 10

    Cart:
      type: object
      properties:
        id:
          type: string
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'
      example:
        id: "609c1fd5810c19729de8612d"
        products:
          - id: "607c191e810c19729de860ea"
            title: "Product A"
            description: "Description of Product A"
            price: 100
            stock: 10
          - id: "607c191e810c19729de860eb"
            title: "Product B"
            description: "Description of Product B"
            price: 200
            stock: 5

    User:
      type: object
      properties:
        id:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        role:
          type: string
      example:
        id: "609c1fd5810c19729de8612d"
        first_name: "John"
        last_name: "Doe"
        email: "john.doe@example.com"
        role: "user"

    Ticket:
      type: object
      properties:
        id:
          type: string
        code:
          type: string
        purchase_datetime:
          type: string
        amount:
          type: number
        purchaser:
          type: string
      example:
        id: "60b8d29581c9b341b16d6e14"
        code: "TICKET-001"
        purchase_datetime: "2024-08-14T12:00:00Z"
        amount: 250.0
        purchaser: "john.doe@example.com"
